URL = "http://dbweb5.fnal.gov:8080/ECL/minerva"
password = "xxxx2009"
user = "minerva_auto"
SWAPDIR="/daqdata"
LOGDIR="/home/minos/automated_ecl/logfiles"                                                                                                                                      
